---
kind: pipeline
type: kubernetes
name: default

environment:
  GOCACHE: /cache/pkg/cache
  GOMODCACHE: /cache/pkg/mod

steps:
  - name: fetch-tags
    image: alpine/git
    commands:
      - git fetch --tags
    resources:
      requests:
        cpu: 250
        memory: 50MiB
      limits:
        cpu: 250
        memory: 100MiB

  - name: test
    image: golang:1.24-alpine
    pull: always
    volumes:
      - name: go
        path: /go
      - name: gopkg
        path: /cache
    commands:
      - go test -v ./...
      - go build ./...
    resources:
      requests:
        cpu: 1000
        memory: 128MiB
      limits:
        cpu: 2000
        memory: 2GiB

  - name: goreleaser
    image: golang:1.24-alpine
    resources:
      requests:
        cpu: 6000
        memory: 2GiB
      limits:
        cpu: 6000
        memory: 8GiB
    volumes:
      - name: go
        path: /go
      - name: gopkg
        path: /cache
    environment:
      GITHUB_TOKEN:
        from_secret: GITHUB_TOKEN
    commands:
      # - go env
      # curl -sf https://goreleaser.com/static/latest
      - apk add bash git
      - ./scripts/update-man-page
      - ./scripts/run-goreleaser
      - echo Done
    depends_on: [test]

  - name: docker
    image: harbor.ntppool.org/ntppool/drone-kaniko:main
    pull: always
    settings:
      repo: ntppool/monitor-api
      registry: harbor.ntppool.org
      tags: "${DRONE_BRANCH},build-${DRONE_BUILD_NUMBER},SHAABBREV,SHA7"
      auto_tag: true
      cache: true
      username:
        from_secret: harbor_username
      password:
        from_secret: harbor_password
    depends_on: [goreleaser]

  - name: upload
    image: plugins/s3
    resources:
      requests:
        cpu: 250
        memory: 64MiB
      limits:
        cpu: 250
        memory: 256MiB
    settings:
      access_key:
        from_secret: s3_access_key
      secret_key:
        from_secret: s3_secret_key
      bucket: geodns
      target: /ntppool-agent/builds/test/${DRONE_BUILD_NUMBER}
      source: dist/*
      strip_prefix: dist/
      endpoint: https://minio-ewr1.develooper.com/
      path_style: true
    when:
      ref:
        - refs/heads/main
        - refs/tags/*
    depends_on: [goreleaser]

  - name: fury-publish
    image: golang:1.24
    resources:
      requests:
        cpu: 250
        memory: 64MiB
      limits:
        cpu: 250
        memory: 256MiB
    environment:
      FURY_TOKEN:
        from_secret: fury_test_token
    commands:
      - ./scripts/fury-publish ntppool-test
    when:
      ref:
        - refs/heads/main
        - refs/tags/*
    depends_on: [goreleaser]

volumes:
  - name: go
    temp: {}
  - name: gopkg
    claim:
      name: go-pkg

trigger:
  event:
    - push
    - tag
    - pull_request

---
kind: pipeline
type: kubernetes
name: publish-production

steps:
  - name: download
    image: fedora:42 # curl version 7.83 or later
    commands:
      - ./scripts/download-release ntppool-agent test/${DRONE_BUILD_PARENT} dist/
    resources:
      requests:
        cpu: 250
        memory: 64MiB
      limits:
        cpu: 250
        memory: 256MiB

  - name: upload
    image: plugins/s3
    resources:
      requests:
        cpu: 250
        memory: 64MiB
      limits:
        cpu: 250
        memory: 256MiB
    settings:
      access_key:
        from_secret: s3_access_key
      secret_key:
        from_secret: s3_secret_key
      bucket: geodns
      target: /ntppool-agent/builds/release/${DRONE_BUILD_PARENT}
      source: dist/*
      strip_prefix: dist/
      endpoint: https://minio-ewr1.develooper.com/
      path_style: true
    depends_on: ["download"]

  - name: fury-publish
    image: golang:1.24
    resources:
      requests:
        cpu: 250
        memory: 64MiB
      limits:
        cpu: 250
        memory: 256MiB
    environment:
      FURY_TOKEN:
        from_secret: fury_token
    commands:
      - ./scripts/fury-publish ntppool
    depends_on: ["download"]

trigger:
  event:
    - promote
  target:
    - publish
---
kind: signature
hmac: 53072f39b6eeed5d2bb406b3ab5e901dc8cbda82f92e2f71312992e695c287f0

...
