before:
  # we don't want this in the CI environment
  #hooks:
  #  - go mod tidy
  #  - go generate ./...
builds:
  - main: ./client/cmd/ntppool-monitor/
    id: ntppool-monitor
    binary: ntppool-monitor
    env:
      - CGO_ENABLED=0
    goos:
      - linux
      - freebsd
      - darwin
    ldflags:
      - -s -w
      - -X go.ntppool.org/monitor/version.VERSION={{.Version}}
      - -X go.ntppool.org/monitor/version.gitVersion={{.ShortCommit}}
      - -X go.ntppool.org/monitor/version.buildTime={{.Date}}

  - main: ./server/cmd/monitor-api/
    id: monitor-api
    binary: monitor-api
    env:
      - CGO_ENABLED=0
    goos:
      - linux
      - freebsd
      - darwin
    ldflags:
      - -s -w
      - -X go.ntppool.org/monitor/version.VERSION={{.Version}}
      - -X go.ntppool.org/monitor/version.gitVersion={{.ShortCommit}}
      - -X go.ntppool.org/monitor/version.buildTime={{.Date}}

  - main: ./scorer/cmd/monitor-scorer/
    id: monitor-scorer
    binary: monitor-scorer
    env:
      - CGO_ENABLED=0
    goos:
      - linux
    ldflags:
      - -s -w
      - -X go.ntppool.org/monitor/version.VERSION={{.Version}}
      - -X go.ntppool.org/monitor/version.gitVersion={{.ShortCommit}}
      - -X go.ntppool.org/monitor/version.buildTime={{.Date}}

archives:
  - id: a1
    allow_different_binary_count: true
  # files:
  #   - LICENSE.txt
  #   - ./client/cmd/ntppool-monitor/README.md

checksum:
  name_template: "checksums.txt"
snapshot:
  name_template: '{{ .Tag }}{{ if index .Env "DRONE_BUILD_NUMBER" }}-{{ .Env.DRONE_BUILD_NUMBER }}{{ else }}-next{{ end }}'
changelog:
  sort: asc
  filters:
    exclude:
      - "^docs:"
      - "^test:"

nfpms:
  - id: ntppool-monitor

    # Name of the package.
    # Defaults to `ProjectName`.
    package_name: ntppool-monitor

    #file_name_template: "{{ .ProjectName }}_{{ .Version }}_{{ .Os }}_{{ .Arch }}"
    file_name_template: "{{ .ConventionalFileName }}"

    vendor: NTP Pool Project
    homepage: https://www.ntppool.org/
    maintainer: Ask Bjørn Hansen <ask@develooper.com>
    description: Monitoring daemon for the NTP Pool
    license: Apache 2.0
    formats:
      - deb
      - rpm
      - apk
    dependencies:
      - chrony
    bindir: /usr/bin

    overrides:
      deb:
        dependencies:
          - "ntp | chrony"

      rpm:
        # this is supposed to work, but I couldn't figure it out.
        # so, ... chrony only on redhat flavors for now.
        #dependencies:
        #  - (ntp or chrony)

    contents:
      - src: "scripts/ntppool-monitor@.service"
        dst: "/etc/systemd/system/ntppool-monitor@.service"

      - src: "scripts/enable-ntppool-monitors"
        dst: "/usr/bin/enable-ntppool-monitors"

      - src: "scripts/defaults"
        dst: "/etc/default/ntppool-monitor.sample"
        type: config

      - src: "scripts/defaults"
        dst: "/etc/default/ntppool-monitor"
        type: config|noreplace

    scripts:
      preinstall: scripts/preinstall.sh
      postinstall: scripts/postinstall.sh
