# yaml-language-server: $schema=https://goreleaser.com/static/schema.json
version: 2

builds:
  - main: ./client/cmd/ntppool-monitor/
    id: ntpmon
    binary: ntpmon
    env:
      - CGO_ENABLED=0
    goos:
      - linux
      - freebsd
      - darwin
    ldflags:
      - -s -w
      - -X go.ntppool.org/common/version.VERSION={{.Version}}

  - main: ./server/cmd/monitor-api/
    id: monitor-api
    binary: monitor-api
    env:
      - CGO_ENABLED=0
    goos:
      - linux
      - freebsd
      - darwin
    ldflags:
      - -s -w
      - -X go.ntppool.org/common/version.VERSION={{.Version}}

  - main: ./scorer/cmd/monitor-scorer/
    id: monitor-scorer
    binary: monitor-scorer
    env:
      - CGO_ENABLED=0
    goos:
      - linux
    ldflags:
      - -s -w
      - -X go.ntppool.org/common/version.VERSION={{.Version}}

archives:
  - id: a1
    allow_different_binary_count: true
  # files:
  #   - LICENSE.txt
  #   - ./client/cmd/ntppool-monitor/README.md

checksum:
  name_template: "checksums.txt"
snapshot:
  version_template: '{{ .Tag }}{{ if index .Env "DRONE_BUILD_NUMBER" }}-{{ .Env.DRONE_BUILD_NUMBER }}{{ else }}-next{{ end }}'
changelog:
  sort: asc
  filters:
    exclude:
      - "^docs:"
      - "^test:"

nfpms:
  - id: ntpmon

    package_name: ntpmon

    #file_name_template: "{{ .ProjectName }}_{{ .Version }}_{{ .Os }}_{{ .Arch }}"
    file_name_template: "{{ .ConventionalFileName }}"

    vendor: NTP Pool Project
    homepage: https://www.ntppool.org/
    maintainer: Ask Bjørn Hansen <ask@develooper.com>
    description: Monitoring daemon for the NTP Pool
    license: Apache 2.0
    formats:
      - deb
      - rpm
      - apk
    dependencies:
      - chrony
    bindir: /usr/bin

    overrides:
      deb:
        dependencies:
          - "ntp | chrony"

      rpm:
        # this is supposed to work, but I couldn't figure it out.
        # so, ... chrony only on redhat flavors for now.
        #dependencies:
        #  - (ntp or chrony)

    contents:
      - src: "scripts/ntpmon@.service"
        dst: "/etc/systemd/system/ntpmon@.service"

      - src: "scripts/enable-ntppool-monitors"
        dst: "/usr/bin/enable-ntppool-monitors"

      - src: "scripts/defaults"
        dst: "/etc/default/ntpmon.sample"
        type: config

      - src: "scripts/defaults"
        dst: "/etc/default/ntpmon"
        type: config|noreplace

    scripts:
      preinstall: scripts/preinstall.sh
      postinstall: scripts/postinstall.sh
